version: '3.6'

services: 
  python:
    build:
      context: ./dcoops
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - type: bind
        source: .
        target: /discord
    links:
      - 'mysql'

  mysql:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=discord
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    volumes:
      - type: volume
        source: d4e21b5cb2d3eee9ffffa2e040bd701c11108e32f1c1247fa24a28b8e6c667ea
        target: /var/lib/mysql

volumes: 
  d4e21b5cb2d3eee9ffffa2e040bd701c11108e32f1c1247fa24a28b8e6c667ea:
    external: true

networks:
  core-network: 
    external: true
  dcoops-network:
    external: false