"""empty message

Revision ID: 7a8c46d27526
Revises: 98c71e9ada6c
Create Date: 2020-12-28 01:11:06.702653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8c46d27526'
down_revision = '98c71e9ada6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.Column('file_url', sa.String(length=256), nullable=False),
    sa.Column('server', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
