"""empty message

Revision ID: 99fc069019f2
Revises: a90472f1fca4
Create Date: 2021-07-27 11:15:01.071314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fc069019f2'
down_revision = 'a90472f1fca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('server', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('server'),
    sa.UniqueConstraint('server')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
