"""empty message

Revision ID: a90472f1fca4
Revises: 13dc175e770a
Create Date: 2020-12-28 14:19:09.195229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90472f1fca4'
down_revision = '13dc175e770a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.Column('file_url', sa.String(length=256), nullable=False),
    sa.Column('server', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'server')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binds')
    # ### end Alembic commands ###
