"""User generated messaging

Revision ID: d08eae18757d
Revises: 99fc069019f2
Create Date: 2021-11-28 20:35:29.602844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd08eae18757d'
down_revision = '99fc069019f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('message_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_messages')
    # ### end Alembic commands ###
